Allfiles/Mod04/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod04/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod04/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod04/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod04/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod04/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod04/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod04/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod04/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod04/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod04/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod04/Labfiles/Starter/Exercise 2/ContosoConf/packages.config
=> init mod04

Allfiles/Mod05/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod05/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod05/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod05/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod05/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod05/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod05/Labfiles/Solution/Exercise 3/ContosoConf/ContosoConf.csproj, Allfiles/Mod05/Labfiles/Solution/Exercise 3/ContosoConf/Web.config, Allfiles/Mod05/Labfiles/Solution/Exercise 3/ContosoConf/packages.config, Allfiles/Mod05/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod05/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod05/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod05/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod05/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod05/Labfiles/Starter/Exercise 2/ContosoConf/packages.config, Allfiles/Mod05/Labfiles/Starter/Exercise 3/ContosoConf/ContosoConf.csproj, Allfiles/Mod05/Labfiles/Starter/Exercise 3/ContosoConf/Web.config, Allfiles/Mod05/Labfiles/Starter/Exercise 3/ContosoConf/packages.config
=> initial mod05

Allfiles/Mod02/Democode/Solution/DemoWebSite/ContactUs.html
=> fixing mod02 demo

Allfiles/Mod06/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod06/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod06/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod06/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod06/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod06/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod06/Labfiles/Solution/Exercise 3/ContosoConf/ContosoConf.csproj, Allfiles/Mod06/Labfiles/Solution/Exercise 3/ContosoConf/Web.config, Allfiles/Mod06/Labfiles/Solution/Exercise 3/ContosoConf/packages.config, Allfiles/Mod06/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod06/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod06/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod06/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod06/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod06/Labfiles/Starter/Exercise 2/ContosoConf/packages.config, Allfiles/Mod06/Labfiles/Starter/Exercise 3/ContosoConf/ContosoConf.csproj, Allfiles/Mod06/Labfiles/Starter/Exercise 3/ContosoConf/Web.config, Allfiles/Mod06/Labfiles/Starter/Exercise 3/ContosoConf/packages.config
=> initial mod06

Allfiles/Mod07/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod07/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod07/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod07/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod07/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod07/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod07/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod07/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod07/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod07/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod07/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod07/Labfiles/Starter/Exercise 2/ContosoConf/packages.config
=> initial mod07

Allfiles/Mod08/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod08/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod08/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod08/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod08/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod08/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod08/Labfiles/Solution/Exercise 3/ContosoConf/ContosoConf.csproj, Allfiles/Mod08/Labfiles/Solution/Exercise 3/ContosoConf/Web.config, Allfiles/Mod08/Labfiles/Solution/Exercise 3/ContosoConf/packages.config, Allfiles/Mod08/Labfiles/Solution/Exercise 3/ContosoConf/schedule.htm, Allfiles/Mod08/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod08/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod08/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod08/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod08/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod08/Labfiles/Starter/Exercise 2/ContosoConf/packages.config, Allfiles/Mod08/Labfiles/Starter/Exercise 3/ContosoConf/ContosoConf.csproj, Allfiles/Mod08/Labfiles/Starter/Exercise 3/ContosoConf/Web.config, Allfiles/Mod08/Labfiles/Starter/Exercise 3/ContosoConf/packages.config
=> initial mod08

Allfiles/Mod09/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod09/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod09/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod09/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod09/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod09/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod09/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod09/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod09/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod09/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod09/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod09/Labfiles/Starter/Exercise 2/ContosoConf/packages.config
=> intial mod09

Allfiles/Mod10/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod10/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod10/Labfiles/Solution/Exercise 1/ContosoConf/index.htm, Allfiles/Mod10/Labfiles/Solution/Exercise 1/ContosoConf/location.htm, Allfiles/Mod10/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod10/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod10/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod10/Labfiles/Solution/Exercise 2/ContosoConf/index.htm, Allfiles/Mod10/Labfiles/Solution/Exercise 2/ContosoConf/location.htm, Allfiles/Mod10/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod10/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod10/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod10/Labfiles/Starter/Exercise 1/ContosoConf/index.htm, Allfiles/Mod10/Labfiles/Starter/Exercise 1/ContosoConf/location.htm, Allfiles/Mod10/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod10/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod10/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod10/Labfiles/Starter/Exercise 2/ContosoConf/index.htm, Allfiles/Mod10/Labfiles/Starter/Exercise 2/ContosoConf/location.htm, Allfiles/Mod10/Labfiles/Starter/Exercise 2/ContosoConf/packages.config
retargeting, nuget update and fixing tags
=> initial mod10

Allfiles/Mod11/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod11/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod11/Labfiles/Solution/Exercise 1/ContosoConf/about.htm, Allfiles/Mod11/Labfiles/Solution/Exercise 1/ContosoConf/index.htm, Allfiles/Mod11/Labfiles/Solution/Exercise 1/ContosoConf/location.htm, Allfiles/Mod11/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod11/Labfiles/Solution/Exercise 1/ContosoConf/schedule.htm, Allfiles/Mod11/Labfiles/Solution/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod11/Labfiles/Solution/Exercise 2/ContosoConf/Web.config, Allfiles/Mod11/Labfiles/Solution/Exercise 2/ContosoConf/about.htm, Allfiles/Mod11/Labfiles/Solution/Exercise 2/ContosoConf/index.htm, Allfiles/Mod11/Labfiles/Solution/Exercise 2/ContosoConf/location.htm, Allfiles/Mod11/Labfiles/Solution/Exercise 2/ContosoConf/packages.config, Allfiles/Mod11/Labfiles/Solution/Exercise 2/ContosoConf/schedule.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod11/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod11/Labfiles/Starter/Exercise 1/ContosoConf/about.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 1/ContosoConf/index.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 1/ContosoConf/location.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 1/ContosoConf/packages.config, Allfiles/Mod11/Labfiles/Starter/Exercise 1/ContosoConf/schedule.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 2/ContosoConf/ContosoConf.csproj, Allfiles/Mod11/Labfiles/Starter/Exercise 2/ContosoConf/Web.config, Allfiles/Mod11/Labfiles/Starter/Exercise 2/ContosoConf/about.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 2/ContosoConf/index.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 2/ContosoConf/location.htm, Allfiles/Mod11/Labfiles/Starter/Exercise 2/ContosoConf/packages.config, Allfiles/Mod11/Labfiles/Starter/Exercise 2/ContosoConf/schedule.htm
retargeting, nuget update and fixing tags
=> initial mod11

Allfiles/Mod14/Labfiles/Solution/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod14/Labfiles/Solution/Exercise 1/ContosoConf/Web.config, Allfiles/Mod14/Labfiles/Solution/Exercise 1/ContosoConf/location.htm, Allfiles/Mod14/Labfiles/Solution/Exercise 1/ContosoConf/packages.config, Allfiles/Mod14/Labfiles/Starter/Exercise 1/ContosoConf/ContosoConf.csproj, Allfiles/Mod14/Labfiles/Starter/Exercise 1/ContosoConf/Web.config, Allfiles/Mod14/Labfiles/Starter/Exercise 1/ContosoConf/location.htm, Allfiles/Mod14/Labfiles/Starter/Exercise 1/ContosoConf/packages.config
retargeting, nuget update and fixing tags
=> initial mod14

Allfiles/Mod05/Democode/fetchWeb/fetchWeb/Scripts/indexScript.js, Allfiles/Mod05/Democode/fetchWeb/fetchWeb/fetchWeb.csproj, Allfiles/Mod05/Democode/fetchWeb/fetchWeb/index.html
DOMContentLoaded event listener added
event listener added to GetPersons button
=> demo code changed

Allfiles/Mod03/Labfiles/Solution/Exercise 1/ContosoConf/scripts/pages/schedule.js, Allfiles/Mod03/Labfiles/Solution/Exercise 2/ContosoConf/scripts/pages/schedule.js, Allfiles/Mod03/Labfiles/Starter/Exercise 1/ContosoConf/scripts/pages/schedule.js, Allfiles/Mod03/Labfiles/Starter/Exercise 2/ContosoConf/scripts/pages/schedule.js
=> module 3 lab

Instructions/20480C_MOD03_DEMO.md
=> mod03 demo 01

Instructions/20480C_MOD01_DEMO.md, Instructions/20480C_MOD01_LAK.md, Instructions/20480C_MOD02_DEMO.md, Instructions/20480C_MOD02_LAK.md, Instructions/20480C_MOD03_DEMO.md, Instructions/20480C_MOD03_LAK.md, Instructions/20480C_MOD04_DEMO.md, Instructions/20480C_MOD04_LAK.md, Instructions/20480C_MOD05_DEMO.md, Instructions/20480C_MOD05_LAK.md, Instructions/20480C_MOD06_DEMO.md, Instructions/20480C_MOD06_LAK.md, Instructions/20480C_MOD07_DEMO.md, Instructions/20480C_MOD07_LAK.md, Instructions/20480C_MOD08_DEMO.md, Instructions/20480C_MOD08_LAK.md, Instructions/20480C_MOD09_DEMO.md, Instructions/20480C_MOD09_LAK.md, Instructions/20480C_MOD10_DEMO.md, Instructions/20480C_MOD10_LAK.md, Instructions/20480C_MOD11_DEMO.md, Instructions/20480C_MOD11_LAK.md, Instructions/20480C_MOD12_DEMO.md, Instructions/20480C_MOD12_LAK.md, Instructions/20480C_MOD13_DEMO.md, Instructions/20480C_MOD13_LAK.md, Instructions/20480C_MOD14_DEMO.md, Instructions/20480C_MOD14_LAK.md
=> instraction added

Instructions/20480C_MOD05_LAB_MANUAL.md
=> CE complete. Ready for SME.

Instructions/20480C_MOD13_LAK.md
CE complete. Ready for SME.
No comments.
=> Apposite 20480 c mod13 lak

Instructions/20480C_MOD13_LAB_MANUAL.md
CE complete. Ready for SME.
No comments.
=> Apposite 20480 c mod13 lm

Instructions/20480C_MOD13_DEMO.md
Ce complete. Ready for SME
No comments.
=> Apposite 20480 c mod13 demo

Instructions/20480C_MOD11_LAK.md
=> Apposite 20480 c mod11 lak

Instructions/20480C_MOD11_LAB_MANUAL.md
=> Apposite 20480 c mod11 lm

Instructions/20480C_MOD11_DEMO.md
=> Apposite 20480 c mod11 demo

Instructions/20480C_MOD10_LAK.md
=> Apposite 20480 c mod10 lak

Instructions/20480C_MOD10_LAB_MANUAL.md
=> Apposite 20480 c mod10 lm

Instructions/20480C_MOD10_DEMO.md
=> Apposite 20480 c mod10 demo

Instructions/20480C_MOD09_LAK.md
=> Apposite 20480 c mod09 lak

Instructions/20480C_MOD09_LAB_MANUAL.md
=> Apposite 20480 c mod09 lm

Instructions/20480C_MOD09_DEMO.md
=> Apposite 20480 c mod09 demo

Instructions/20480C_MOD07_LAK.md
=> Apposite 20480 c mod07 lak

Instructions/20480C_MOD07_LAB_MANUAL.md
=> Apposite 20480 c mod07 lm

Instructions/20480C_MOD07_DEMO.md
CE complete. Ready for SME. Comments in line.
=> Apposite 20480 c mod07 demo

Instructions/20480C_MOD12_LAB_MANUAL.md
=> 20480C | Mod 12 | LM

Instructions/20480C_MOD12_DEMO.md
=> 20480C | Mod 12 | Demo

Instructions/20480C_MOD12_LAK.md
=> 20480C | Mod 12 | LAK

Instructions/20480C_MOD02_DEMO.md
=> 20480C | Mod 02 | Demo

Instructions/20480C_MOD02_LAB_MANUAL.md
=> 20480C | Mod 02 | LM

Instructions/20480C_MOD06_LAB_MANUAL.md
=> 20480C | Mod06 | Lab

Instructions/20480C_MOD03_LAB_MANUAL.md
=> 20480C | Mod03 | LM

Instructions/20480C_MOD03_LAK.md
=> 20480C | Mod03 | LAK

Instructions/20480C_MOD08_DEMO.md
=> 20480C | Mod08 | Demo

Instructions/20480C_MOD08_LAB_MANUAL.md
=> 20480C | Mod08 | LM

Instructions/20480C_MOD08_LAK.md
=> 20480C | Mod08 | LAK

Instructions/20480C_MOD01_DEMO.md
=> 20480C | Mod01 | Demo

Instructions/20480C_MOD14_LAK.md
=> Apposite 20480 c mod14 lak

Instructions/20480C_MOD02_LAK.md
=> mod02-lab-fixing-bugs

Instructions/20480C_MOD05_LAB_MANUAL.md
=> 20480C | Mod05 | LM

Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial.sln, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/Properties/AssemblyInfo.cs, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/Web.Debug.config, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/Web.Release.config, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/Web.config, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/build-tutorial.csproj, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/employees.json, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/index.html, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/packages.config, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/scripts/app.js, Allfiles/Mod15/DemoCode/build-tutorial/build-tutorial/styles/styles.css, Instructions/20480C_MOD15_DEMO.md
demo 2 added instructions and demo code
=> module 15 demos
